version: 0.0
os: linux
files:
 - source: /index.html
   destination: /usr/share/nginx/html
 - source: /style.css
   destination: /usr/share/nginx/html
 - source: /avatarmaker.png
   destination: /usr/share/nginx/html
hooks:
 BeforeInstall:
   - location: AWS-CodePipeline-and-CodeDeploy/scripts/before_install.sh
     timeout: 300
     runas: root
 AfterInstall:
   - location: AWS-CodePipeline-and-CodeDeploy/scripts/after_install.sh
     timeout: 300 
     runas: root
